line_follower:
  ros__parameters:

    # TOPICS
    camera_topic: /video_source/yolo/compressed
    line_error_topic: /line_error
    debug_view: false

    # ROI
    crop_percent: 0.20

traffic_light_detector:
  ros__parameters:

    kernel_size:       6
    min_blob_area:     2000
    min_circularity:   0.95

    # Topics
    camera_topic:      /video_source/raw
    state_topic:       /traffic_light/state
    debug_image:       false


image_compressor:
  ros__parameters:

    input_topic: /video_source/raw

    output_topic: /video_source/yolo/compressed

    width: 416
    height: 416

    jpeg_quality: 40

    grayscale: true
